### ISSUE TITLE
New publisher discovered on topic 'left/right', offering incompatible QoS. No messages will be received from it. Last incompatible policy: RELIABILITY

### ISSUE THREAD

**Issue by l4es** [ros-perception/image_pipeline#1042]
Hi,

I attempt to perform the stereo camera calibration for my own Jetson Orin NX/Jepack-5.12/ROS2 Humble based stereo camera : 

```
$ ros2 topic list
/baro/pressure
/camera/assemble/image_raw
/camera/assemble/image_raw/compressed
/camera/left/camera_info
/camera/left/image_raw
/camera/left/image_raw/compressed
/camera/right/camera_info
/camera/right/image_raw
/camera/right/image_raw/compressed
```

by launching the following command : 
`$ ros2 run camera_calibration cameracalibrator --approximate 0.1 --size 8x6 --square 0.108 right:=/camera/right/image_raw left:=/camera/left/image_raw right_camera:=/camera/right left_camera:=/camera/left`

which gave the following log : 
```
[WARN] [1731403429.652019518] [rcl]: Found remap rule 'right:=/camera/right/image_raw'. This syntax is deprecated. Use '--ros-args --remap right:=/camera/right/image_raw' instead.
[WARN] [1731403429.652053407] [rcl]: Found remap rule 'left:=/camera/left/image_raw'. This syntax is deprecated. Use '--ros-args --remap left:=/camera/left/image_raw' instead.
[WARN] [1731403429.652066111] [rcl]: Found remap rule 'right_camera:=/camera/right'. This syntax is deprecated. Use '--ros-args --remap right_camera:=/camera/right' instead.
[WARN] [1731403429.652075232] [rcl]: Found remap rule 'left_camera:=/camera/left'. This syntax is deprecated. Use '--ros-args --remap left_camera:=/camera/left' instead.
[WARN] [1731403429.660325344] [rcl]: Found remap rule 'right:=/camera/right/image_raw'. This syntax is deprecated. Use '--ros-args --remap right:=/camera/right/image_raw' instead.
[WARN] [1731403429.660359490] [rcl]: Found remap rule 'left:=/camera/left/image_raw'. This syntax is deprecated. Use '--ros-args --remap left:=/camera/left/image_raw' instead.
[WARN] [1731403429.660370786] [rcl]: Found remap rule 'right_camera:=/camera/right'. This syntax is deprecated. Use '--ros-args --remap right_camera:=/camera/right' instead.
[WARN] [1731403429.660380482] [rcl]: Found remap rule 'left_camera:=/camera/left'. This syntax is deprecated. Use '--ros-args --remap left_camera:=/camera/left' instead.
Waiting for service camera/set_camera_info ...
OK
Waiting for service left_camera/set_camera_info ...
OK
Waiting for service right_camera/set_camera_info ...
OK
[WARN] [1731403444.972188340] [cameracalibrator]: New publisher discovered on topic 'left', offering incompatible QoS. No messages will be received from it. Last incompatible policy: RELIABILITY
[WARN] [1731403444.973163030] [cameracalibrator]: New publisher discovered on topic 'right', offering incompatible QoS. No messages will be received from it. Last incompatible policy: RELIABILITY
```
But nothing appeared on the GUI despite that the checkerboard did appear on rqt for both /camera/left/image_raw /camera/right/image_raw topics.

Checking the topic info gave : 
```

~$ ros2 topic info -v /camera/left/image_raw
Type: sensor_msgs/msg/Image

Publisher count: 1

Node name: RTR_cam_sync_imu
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 01.0f.1b.26.ad.3c.d3.28.01.00.00.00.00.00.13.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 1

Node name: cameracalibrator
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 01.0f.1b.26.b5.46.15.77.01.00.00.00.00.00.17.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

~$ ros2 topic info -v /camera/right/image_raw
Type: sensor_msgs/msg/Image

Publisher count: 1

Node name: RTR_cam_sync_imu
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 01.0f.1b.26.ad.3c.d3.28.01.00.00.00.00.00.14.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 1

Node name: cameracalibrator
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 01.0f.1b.26.b5.46.15.77.01.00.00.00.00.00.18.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
```

Update : Now that I can change the QoS settings of both topics images : 
```
~$ ros2 topic info -v /camera/left/image_raw
Type: sensor_msgs/msg/Image

Publisher count: 1

Node name: RTR_cam_sync_imu
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 01.0f.1b.26.0f.5e.00.d9.01.00.00.00.00.00.13.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 1

Node name: cameracalibrator
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: SUBSCRIPTION
GID: 01.0f.1b.26.10.61.44.27.01.00.00.00.00.00.17.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

~$ ros2 topic info -v /camera/right/image_raw
Type: sensor_msgs/msg/Image

Publisher count: 1

Node name: RTR_cam_sync_imu
Node namespace: /
Topic type: sensor_msgs/msg/Image
Endpoint type: PUBLISHER
GID: 01.0f.1b.26.0f.5e.00.d9.01.00.00.00.00.00.14.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 0
```
 And I do not see the message in the title anymore. However, nothing happened on the GUI windows.

Could someone help, please ?
Khang

**Comment by mikeferguson** [comment]
This really isn't debuggable as-is. Please post:

 * an image of what the GUI looks like
 * check the terminal for any logged errors and post them here
 * note which ROS distribution you are using, and whether from source or pre-built Debian packages

**Comment by l4es** [comment]
Hi @mikeferguson,

Sorry for not providing more detail. Please find my answer inline 

RQT shows checkerboard inside of both frames : 
![Screenshot from 2024-11-12 21-58-39](https://github.com/user-attachments/assets/40cb4569-8d45-47b2-961d-f342c72673fe)

> an image of what the GUI looks like

![Screenshot from 2024-11-12 21-59-44](https://github.com/user-attachments/assets/0e4f4813-5c60-4921-b4be-92b1e7608713)

![Screenshot from 2024-11-12 22-07-22](https://github.com/user-attachments/assets/31b30f2a-2944-47df-aaca-eac0aa6f18df)


> check the terminal for any logged errors and post them here

```
~$ ros2 run camera_calibration cameracalibrator --approximate 0.1 --size 8x6 --square 0.108 --ros-args --remap right:=/stereo/right/image_raw --remap left:=/camera/left/image_raw --remap right_camera:=/camera/right --remap left_camera:=/camera/left
Waiting for service camera/set_camera_info ...
OK
Waiting for service left_camera/set_camera_info ...
OK
Waiting for service right_camera/set_camera_info ...
OK
```
> note which ROS distribution you are using, and whether from source or pre-built Debian packages
ROS2 Humble installed from pre-built .deb packages with following reference : https://qiita.com/ntrlmt/items/50b49fb43b4439ac165b

Potentially, the image_pipeline for Nvidia Jetson/Jetpack could be this one  : https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_image_pipeline

Update : I found the issue while answering you : it should right:=/camera/right/image_raw  instead of right:=/stereo/right/image_raw 

Thanks,
K

**Comment by mikeferguson** [comment]
Your checkerboard appears to be 7x6 - not 8x6

**Comment by l4es** [comment]
Hi @mikeferguson,

Thanks very much. The checkerboard is now detected.
![Screenshot from 2024-11-12 22-51-00](https://github.com/user-attachments/assets/85da50dc-61e9-47a4-a05b-9dff5742cbe2)
 By the way, for the FoV 185 (D) x 160 (H) x 98 (V),  what should I select the camera model? Should it be fisheye rather than pinhole ? And what is the purpose of the scale, please ? 

I got below error while clicking Calibrate button when fisheye model is selected : 
```
**** Calibrating ****
mono fisheye calibration...
mono fisheye calibration...
stereo fisheye calibration...
Traceback (most recent call last):
  File "/opt/ros/humble/lib/python3.8/site-packages/camera_calibration/camera_calibrator.py", line 278, in on_mouse
    self.c.do_calibration()
  File "/opt/ros/humble/lib/python3.8/site-packages/camera_calibration/calibrator.py", line 1399, in do_calibration
    self.cal_fromcorners(self.good_corners)
  File "/opt/ros/humble/lib/python3.8/site-packages/camera_calibration/calibrator.py", line 1164, in cal_fromcorners
    cv2.fisheye.stereoCalibrate(opts, lipts, ripts,
cv2.error: OpenCV(4.2.0) ../modules/calib3d/src/fisheye.cpp:1023: error: (-215:Assertion failed) abs_max < threshold in function 'stereoCalibrate'
```


Thanks,
Khang

**Comment by mikeferguson** [comment]
Looks like you're up and running if you switch to regular pinhole - I'm not sure fisheye calibration actually works in Humble - I've personally never used fisheye (in any distro)
