### ISSUE TITLE
cameracheck.py error when checkerboard gets in focus.

### ISSUE THREAD

**Issue by bjornph** [ros-perception/image_pipeline#134]
Running ubuntu 14.04 and ros  indigo.

I  run
 <code>rosrun camera_calibration cameracheck.py --size 11x7 --square 0.04 monocular:=/usb_cam</code>
it prints no  chessboard continiusly when there's no chessboard in my image  frame. When it does get it fails  with:
<code>
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/camera_calibration/cameracheck.py", line 83, in run
    self.function(m)
  File "/opt/ros/indigo/lib/camera_calibration/cameracheck.py", line 156, in handle_monocular
    if C:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()</code>

What's wrong?

**Comment by njzhangyifei** [comment]
This issue should have been fixed by https://github.com/ros-perception/image_pipeline/commit/75ecbaa018017a3868cbe0922ad3f04aa4338b1d

**Comment by vrabaud** [comment]
indeed and that just got released in shadow-fixed. Fixed in 1.12.14
