### ISSUE TITLE
bug with standard groovy installation on ubuntu 12.10

### ISSUE THREAD

**Issue by aplyer** [ros-perception/image_pipeline#18]
$> rosrun camera_calibration cameracalibrator.py --size 6x7 --square 0.108 image:=/stereo/left/image_mono

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/opt/ros/groovy/lib/camera_calibration/cameracalibrator.py", line 68, in run
    self.function(m)
  File "/opt/ros/groovy/lib/camera_calibration/cameracalibrator.py", line 134, in handle_monocular
    drawable = self.c.handle_msg(msg)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 736, in handle_msg
    rgb = self.mkgray(msg)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 270, in mkgray
    rgb = self.br.imgmsg_to_cv(msg, "bgr8")
  File "/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge/core.py", line 101, in imgmsg_to_cv
    source_type = self.encoding_as_cvtype(img_msg.encoding)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge/core.py", line 73, in encoding_as_cvtype
    from cv_bridge.boost.cv_bridge_boost import getCvType
ImportError: No module named cv_bridge_boost

**Comment by aplyer** [comment]
I don't find any cv_bridge_boost python file... 
the cv_bridge directory of my groovy instalation is :

$> tree /opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge
/opt/ros/groovy/lib/python2.7/dist-packages/cv_bridge
├── boost
│   ├── **init**.py
│   └── **init**.pyc
├── core.py
├── core.pyc
├── **init**.py
└── **init**.pyc

**Comment by vrabaud** [comment]
thx for reporting. I fixed it in cv_bridge 1.10.4 which I just released
