### ISSUE TITLE
cameracheck.py failed

### ISSUE THREAD

**Issue by aclodic** [ros-perception/image_pipeline#205]
On our PR2 (running indigo), 
trying to test the narrow_stereo calibration leads to this error:

@c1:~/catkin_indigo_calib_ws$ rosrun camera_calibration cameracheck.py stereo:=narrow_stereo --size=7x6 --square=0.108
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/aclodic/catkin_indigo_calib_ws/src/image_pipeline/camera_calibration/nodes/cameracheck.py", line 83, in run
    self.function(m)
  File "/home/aclodic/catkin_indigo_calib_ws/src/image_pipeline/camera_calibration/nodes/cameracheck.py", line 190, in handle_stereo
    if L and R:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by aclodic** [comment]
and it does the same with a freshly installed package:

@c1:~/catkin_indigo_calib$ rosrun camera_calibration cameracheck.py stereo:=wide_stereo --size=7x6 --square=0.108
no chessboard
no chessboard
no chessboard
no chessboard
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/ros/indigo/lib/camera_calibration/cameracheck.py", line 83, in run
    self.function(m)
  File "/opt/ros/indigo/lib/camera_calibration/cameracheck.py", line 190, in handle_stereo
    if L and R:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
