### ISSUE TITLE
cameracalibrator.py crashes when "Calibrate" is pushed.

### ISSUE THREAD

**Issue by ahendrix** [ros-perception/image_pipeline#21]
Once a sufficient number of samples are captured and the calibration matrix is calculated, cameracalibrator.py crashes with the following trace:

```
OpenCV Error: Assertion failed (src.channels() == dst.channels()) in cvCopy, file /tmp/buildd/ros-groovy-opencv2-2.4.4-1precise-20130301-2019/modules/core/src/copy.cpp, line 575
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/opt/ros/groovy/lib/camera_calibration/cameracalibrator.py", line 68, in run
    self.function(m)
  File "/opt/ros/groovy/lib/camera_calibration/cameracalibrator.py", line 136, in handle_monocular
    self.redraw_monocular(drawable)
  File "/opt/ros/groovy/lib/camera_calibration/cameracalibrator.py", line 248, in redraw_monocular
    cv.Copy(drawable.scrib, cv.GetSubRect(display, (0,0,width,height)))
error: src.channels() == dst.channels()
```

This appears to happen because the calibration switches from color to grayscale once it's calibrated. This appears to be related to the following changes:

https://github.com/ros-perception/image_pipeline/commit/907bab81d232b25b8a0ad68a43ca1d02e9406501
https://github.com/ros-perception/image_pipeline/commit/bf65e373eea7c56adb83c214cbcf5dab1b96cdc0

**Comment by ahendrix** [comment]
I have a fork were I'm working on fixing this: https://github.com/ahendrix/image_pipeline

I have a working fix for this issue, but I want to test the stereo calibration as well before I merge things in.

**Comment by ahendrix** [comment]
Confirmed; stereo and monocular calibration both have this bug in the current release.
