### ISSUE TITLE
Compile failure on OSX

### ISSUE THREAD

**Issue by walchko** [ros-perception/image_pipeline#27]
I had issues with stereo_image_proc and image_proc. Building ROS from source, I had to add find_package(Boost REQUIRED COMPONENT thread) to CMakeLists.txt and #include<boost/thread/lock_guard.hpp> to each file that used lock_guard.

**Comment by vrabaud** [comment]
Weird, we have active development on OSX. Would you mind writing a pull request so that I do not miss any file ? Thx.

**Comment by walchko** [comment]
Done!

**Comment by vrabaud** [comment]
we still need to pull the pull request :) Can you please copy/paste you error: your fix works but I am afraid the error should be fixed upstream to be clean.

**Comment by vrabaud** [comment]
Also, are you using Groovy ? which OSX do you have ? @wjwwood  , can you confirm it does not compile on your OSX ? Thx

**Comment by wjwwood** [comment]
I'll try to test that today.

**Comment by walchko** [comment]
I did the pull ... also:

OSX 10.8.3
ROS Groovy full-desktop install, but I had to delete some packages because they don't work well on OSX (e.g., fcl, moveit, tf2_*, etc). 
Thanks!

**Comment by vrabaud** [comment]
yes, thank you, but as I mentioned on th pull request: "That seems very weird that we need it in side the code: that means somebody does not export those. Can you please copy/paste your error ? Thx"
The error is probably upstream, please send me your error.

**Comment by walchko** [comment]
Sorry … I fixed this and installed Groovy already. I have to go back through the install process to reproduce this. I will try to reinstall this weekend maybe in order to reproduce the error.

**Comment by vrabaud** [comment]
Thx ! I really appreciate.

**Comment by walchko** [comment]
Here ya go!

``` bash
<== Finished processing package [161 of 170]: 'driver_base'
==> Processing catkin package: 'image_proc'
==> Creating build directory: 'build_isolated/image_proc'
==> Building with env: '/Users/kevin/tmp/reinstall/install_isolated/env.sh'
==> cmake /Users/kevin/tmp/reinstall/src/image_proc -DCATKIN_DEVEL_PREFIX=/Users/kevin/tmp/reinstall/devel_isolated/image_proc -DCMAKE_INSTALL_PREFIX=/Users/kevin/tmp/reinstall/install_isolated
-- The C compiler identification is Clang 4.2.0
-- The CXX compiler identification is Clang 4.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /Users/kevin/tmp/reinstall/devel_isolated/image_proc
-- Using CMAKE_PREFIX_PATH: /Users/kevin/tmp/reinstall/install_isolated;/opt/ros/groovy
-- This workspace overlays: /Users/kevin/tmp/reinstall/install_isolated;/opt/ros/groovy
-- Found PythonInterp: /usr/bin/python (found version "2.7.2") 
-- Found PY_em: /Library/Python/2.7/site-packages/em.pyc  
-- Found gtest: gtests will be built
-- Using CATKIN_TEST_RESULTS_DIR: /Users/kevin/tmp/reinstall/build_isolated/image_proc/test_results
-- catkin 0.5.65
-- dynamic_reconfigure built cfg/CropDecimate.cfg: Generating reconfiguration files for CropDecimate in image_proc
Wrote header file in /Users/kevin/tmp/reinstall/devel_isolated/image_proc/include/image_proc/CropDecimateConfig.h
-- dynamic_reconfigure built cfg/Debayer.cfg: Generating reconfiguration files for Debayer in image_proc
Wrote header file in /Users/kevin/tmp/reinstall/devel_isolated/image_proc/include/image_proc/DebayerConfig.h
-- dynamic_reconfigure built cfg/Rectify.cfg: Generating reconfiguration files for Rectify in image_proc
Wrote header file in /Users/kevin/tmp/reinstall/devel_isolated/image_proc/include/image_proc/RectifyConfig.h
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kevin/tmp/reinstall/build_isolated/image_proc
==> make -j2 -l2 in '/Users/kevin/tmp/reinstall/build_isolated/image_proc'
Scanning dependencies of target image_proc_gencfg
[ 30%] Built target image_proc_gencfg
Scanning dependencies of target image_proc
[ 40%] Building CXX object CMakeFiles/image_proc.dir/src/libimage_proc/processor.cpp.o
[ 50%] Building CXX object CMakeFiles/image_proc.dir/src/nodelets/debayer.cpp.o
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:94:10: error: 
      no member named 'lock_guard' in namespace 'boost'
  boost::lock_guard<boost::mutex> lock(connect_mutex_);
  ~~~~~~~^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:94:33: error: 
      expected '(' for function-style cast or type construction
  boost::lock_guard<boost::mutex> lock(connect_mutex_);
                    ~~~~~~~~~~~~^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:94:35: error: 
      use of undeclared identifier 'lock'
  boost::lock_guard<boost::mutex> lock(connect_mutex_);
                                  ^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:102:10: error: 
      no member named 'lock_guard' in namespace 'boost'
  boost::lock_guard<boost::mutex> lock(connect_mutex_);
  ~~~~~~~^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:102:33: error: 
      expected '(' for function-style cast or type construction
  boost::lock_guard<boost::mutex> lock(connect_mutex_);
                    ~~~~~~~~~~~~^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:102:35: error: 
      use of undeclared identifier 'lock'
  boost::lock_guard<boost::mutex> lock(connect_mutex_);
                                  ^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:187:16: error: 
      no member named 'lock_guard' in namespace 'boost'
        boost::lock_guard<boost::recursive_mutex> lock(config_mutex_);
        ~~~~~~~^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:187:49: error: 
      expected '(' for function-style cast or type construction
        boost::lock_guard<boost::recursive_mutex> lock(config_mutex_);
                          ~~~~~~~~~~~~~~~~~~~~~~^
/Users/kevin/tmp/reinstall/src/image_proc/src/nodelets/debayer.cpp:187:51: error: 
      use of undeclared identifier 'lock'
        boost::lock_guard<boost::recursive_mutex> lock(config_mutex_);
                                                  ^
9 errors generated.
make[2]: *** [CMakeFiles/image_proc.dir/src/nodelets/debayer.cpp.o] Error 1
make[1]: *** [CMakeFiles/image_proc.dir/all] Error 2
make: *** [all] Error 2
make: INTERNAL: Exiting with 3 jobserver tokens available; should be 2!
Traceback (most recent call last):
  File "./src/catkin/bin/../python/catkin/builder.py", line 658, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "./src/catkin/bin/../python/catkin/builder.py", line 443, in build_package
    install, jobs, force_cmake, quiet, last_env, cmake_args, make_args
  File "./src/catkin/bin/../python/catkin/builder.py", line 297, in build_catkin_package
    run_command(make_cmd, build_dir, quiet)
  File "./src/catkin/bin/../python/catkin/builder.py", line 186, in run_command
    raise subprocess.CalledProcessError(proc.returncode, ' '.join(cmd))
CalledProcessError: Command '/Users/kevin/tmp/reinstall/install_isolated/env.sh make -j2 -l2' returned non-zero exit status 2
<== Failed to process package 'image_proc': 
  Command '/Users/kevin/tmp/reinstall/install_isolated/env.sh make -j2 -l2' returned non-zero exit status 2

Reproduce this error by running:
==> /Users/kevin/tmp/reinstall/install_isolated/env.sh make -j2 -l2

Command failed, exiting.
```

**Comment by vrabaud** [comment]
thx a bunch, you were totally right. Maybe the includes got changed in a recent Boost. We only tested up to 1.48

**Comment by vrabaud** [comment]
indeed, your changes are only supported by 1.53. I added the proper ifdef around your code to make it work on all platforms.
