### ISSUE TITLE
cameracheck.py error with kinect/ir topic

### ISSUE THREAD

**Issue by bassofil** [ros-perception/image_pipeline#31]
When running

```
rosrun camera_calibration cameracheck.py --size 7x5 monocular:=/camera/ir image:=image_raw
```

I get the following error

```
OpenCV Error: Assertion failed (src.depth() == dst.depth()) in cvCvtColor, file /tmp/buildd/ros-groovy-opencv2-2.4.5-2precise-20130519-1747/modules/imgproc/src/color.cpp, line 3921
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/opt/ros/groovy/lib/camera_calibration/cameracheck.py", line 84, in run
    self.function(m)
  File "/opt/ros/groovy/lib/camera_calibration/cameracheck.py", line 158, in handle_monocular
    C = self.image_corners(rgb)
  File "/opt/ros/groovy/lib/camera_calibration/cameracheck.py", line 145, in image_corners
    (ok, corners, b) = self.mc.get_corners(im)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 378, in get_corners
    (ok, corners) = _get_corners(img, b, refine)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 153, in _get_corners
    cv.CvtColor(img, mono, cv.CV_BGR2GRAY)
error: src.depth() == dst.depth()
```

Obviously, the following command works.

```
rosrun camera_calibration cameracheck.py --size 7x5 monocular:=/camera/rgb image:=image
```

I'm using Ubuntu 12.04 with ROS Groovy.

**Comment by chadrockey** [comment]
I think @stwirth can help with this.

**Comment by stwirth** [comment]
This looks like a bug in cv_bridge to me, @vrabaud might have a look. I submitted a pull request for a workaround.
