### ISSUE TITLE
Camera calibration not saving tarfile

### ISSUE THREAD

**Issue by miquelmassot** [ros-perception/image_pipeline#68]
Hi,

when I've tried to save a calibration using the SAVE button, python outputs:

Traceback (most recent call last):
  File "/opt/ros/hydro/lib/camera_calibration/cameracalibrator.py", line 205, in on_mouse
    self.c.do_save()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 511, in do_save
    self.do_tarfile_save(tf) # Must be overridden in subclasses
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 826, in do_tarfile_save
    taradd(name, cv.EncodeImage(".png", im).tostring())
  File "/opt/ros/hydro/lib/python2.7/dist-packages/camera_calibration/calibrator.py", line 817, in taradd
    s = StringIO.StringIO(buf)
AttributeError: type object '_io.StringIO' has no attribute 'StringIO'

and no file is saved. The code line reported is in https://github.com/ros-perception/image_pipeline/blob/indigo/camera_calibration/src/camera_calibration/calibrator.py#L817

May that be an import error?

**Comment by vrabaud** [comment]
could you please replace the line with:
s = StringIO(buf)
and line 36 with :
from cStringIO import StringIO
If that works, please make a pull request with the fixes.

**Comment by vrabaud** [comment]
fixed through #70
