### ISSUE TITLE
Allow circle grid to be used in camera calibration.

### ISSUE THREAD

**Issue by vrabaud** [ros-perception/image_pipeline#7]
in the cameracalibrator.py node

**Comment by ahendrix** [comment]
Specifying --pattern circles appears to be the correct flag for this, but it crashes with:

```
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /tmp/bui
ldd/ros-groovy-opencv2-2.4.4-1precise-20130301-2019/modules/imgproc/src/color.cp
p, line 3326 
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/home/pr2admin/groovy/src/image_pipeline/camera_calibration/nodes/camera
calibrator.py", line 68, in run
    self.function(m)
  File "/home/pr2admin/groovy/src/image_pipeline/camera_calibration/nodes/camera
calibrator.py", line 134, in handle_monocular
    drawable = self.c.handle_msg(msg)
  File "/home/pr2admin/groovy/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 729, in handle_msg
    scrib_mono, corners, downsampled_corners, board, (x_scale, y_scale) = self.downsample_and_detect(gray)
  File "/home/pr2admin/groovy/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 420, in downsample_and_detect
    (ok, corners, board) = self.get_corners(img)
  File "/home/pr2admin/groovy/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 369, in get_corners
    (ok, corners) = _get_circles(img, b, self.pattern)
  File "/home/pr2admin/groovy/src/image_pipeline/camera_calibration/src/camera_calibration/calibrator.py", line 189, in _get_circles
    cv.CvtColor(img, mono, cv.CV_BGR2GRAY)
error: scn == 3 || scn == 4
```

**Comment by ahendrix** [comment]
Tested; confirmed that cameracalibrator.py no longer crashes for circle targets.

Target detection works reasonably well on the asymmetric circle target I have, but I don't have good dimension measurements of it, so I haven't tried to do the calibration calculations.

The circle target doesn't seem to deal as well with high skew or spherical distortion. This may be because my camera has a lot of distortion, it may be the quality of my target, or it may be a flaw in the detector. I don't plan to use it, so I'm not going to worry about it.

I consider this fixed.

**Comment by vrabaud** [comment]
Cool, closing ! Dot patterns usually deals a bit better with skew but not distortion indeed.
Please release for hydro too whenever you release from now on. Thx.
