### ISSUE TITLE
MemoryError on calibration

### ISSUE THREAD

**Issue by pfaion** [ros-perception/image_pipeline#97]
Hello,
apparently the cameracalibrator.py runs out of memory after a while, when I'm calibrating. It continuosly grew on meory consumption, up to 3GB of my 4GB RAM, before it broke.
Does anybody know why this is happening? How can I fix this?
Thx in advance!

I get the error:

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/pfaion/catkin_ws/src/camera_calibration/nodes/cameracalibrator.py", line 93, in run
    self.function(m)
  File "/home/pfaion/catkin_ws/src/camera_calibration/nodes/cameracalibrator.py", line 169, in handle_monocular
    self.redraw_monocular(drawable)
  File "/home/pfaion/catkin_ws/src/camera_calibration/nodes/cameracalibrator.py", line 289, in redraw_monocular
    display = numpy.zeros((max(480, height), width + 100, 3), dtype=numpy.uint8)
MemoryError

OpenCV Error: Insufficient memory (Failed to allocate 3612676 bytes) in OutOfMemoryError, file /home/pfaion/Downloads/opencv-2.4.9/modules/core/src/alloc.cpp, line 52
Traceback (most recent call last):
  File "/home/pfaion/catkin_ws/src/camera_calibration/nodes/cameracalibrator.py", line 244, in on_mouse
    self.c.do_calibration()
  File "/home/pfaion/catkin_ws/src/camera_calibration/src/camera_calibration/calibrator.py", line 747, in do_calibration
    self.cal_fromcorners(self.good_corners)
  File "/home/pfaion/catkin_ws/src/camera_calibration/src/camera_calibration/calibrator.py", line 578, in cal_fromcorners
    flags = self.calib_flags)
cv2.error: /home/pfaion/Downloads/opencv-2.4.9/modules/core/src/alloc.cpp:52: error: (-4) Failed to allocate 3612676 bytes in function OutOfMemoryError

**Comment by vrabaud** [comment]
How big are your images ? I believe it stores them in RAM which could explain this lack of memory.

**Comment by vrabaud** [comment]
I could not reproduce that at all: which version are you using ?
What cameras ? stereo/mono ? Which resolution ? Thx

**Comment by pfaion** [comment]
Apparently the calibrator stores the images that it receives while calibrating in a queue or something (?). The calibration took quite long... several minutes I think. So it received a lot of images in that time, that were all queued in the RAM for whatever reason.
When I kill the image-stream after it started calibrating, the error won't occur and the calibration outputs all the data, but crashes in the end, because it is not able to find the stream again. This solved the problem for me, but should not be necessary!

I am running Ubuntu 14.04 and ros indigo, working with an ASUS Xtion PRO Live, and doing the calibration for RGB and IR channels separately, so only in mono mode. The resolution is 640x480 pixel. I grab and publish the images with the openni2-launch launchfile.

Now that I think about it... I downloaded the latest version of the camera calibration package (1.12.8) and manually included it into my catkin-workspace. Could it be that I need the whole image pipeline of the same version in there?

**Comment by vrabaud** [comment]
Hi, I believe I fixed it in that commit, could you please confirm ? Thx.

**Comment by pfaion** [comment]
I am not able to run the new code. I get the error:

[ERROR] [WallTime: 1410219592.988763] bad callback: <bound method Subscriber.callback of <message_filters.Subscriber instance at 0xb0fd296c>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 688, in _invoke_callback
    cb(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 74, in callback
    self.signalMessage(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/**init**.py", line 56, in signalMessage
    cb(*(msg + args))
  File "/home/pfaion/catkin_ws/src/camera_calibration_fix/nodes/cameracalibrator.py", line 154, in queue_monocular
    except Queue.Empty:
AttributeError: class Queue has no attribute 'Empty'

**Comment by vrabaud** [comment]
sorry for that bad Python, please download the latest version of the file, thx

**Comment by pfaion** [comment]
Now the GUI won't open when I run it. Tried to set the --no-service-check option, still nothing. I get:

('Waiting for service', '/camera/rgb/set_camera_info', '...')
OK
init done 
opengl support available

and then nothing happens. I checked 3 times that the image is actually being published with the topic I specified. Sorry that I cause that much trouble :P

**Comment by pfaion** [comment]
Just wanted to tell that after tomorrow, I will be offline for the next 2 months, so this is my last chance to test anything.
